baseURL = "/"
languageCode = "en-us"
title = "Brand Guidelines"
theme = "brandguide"

[params]
  description = "Brand Guidelines Documentation"
  author = "Your Company"
  company = "Your Company Name"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "colors"
    name = "Colors"
    url = "/colors/"
    weight = 2
  [[menu.main]]
    identifier = "typography"
    name = "Typography"
    url = "/typography/"
    weight = 3
  [[menu.main]]
    identifier = "logo"
    name = "Logo"
    url = "/logo/"
    weight = 4
  [[menu.main]]
    identifier = "imagery"
    name = "Imagery"
    url = "/imagery/"
    weight = 5
  [[menu.main]]
    identifier = "icons"
    name = "Icons"
    url = "/icons/"
    weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
